### ISSUE TITLE
ClientRole is missing?

### ISSUE THREAD

**Issue by mmorales-nubceo** [SurajLad/VideoCall-App-Flutter#3]
Hi @SurajLad nice work with the UI but is there any reason why you're not using ClientRole?
Without this you can't set Broadcast or Audience behaviour in the app or I'm missing something here. I was trying to test your app because mine(I've my own code) suddenly stop working and I'm using same agora_rtc_engine: 1.0.15. Thanks in advance

**Comment by SurajLad** [comment]
Hi @mmorales-nubceo,
1. The reason ClientRole being not used in this project is due to when i developed this project,there was no such option available in plugin initially i used agora_rtc_engine version 1.0.9 to 1.0.13 for development.I believe it got added later on, also it is useful when you need to create Live streaming / Webinar Kind of app. i used the same in this project you can check here :

https://github.com/SurajLad/Webinar_App-Flutter

2. My App Suddenly stopped working due to my agora.io project got inactive state by mistake, i have activated the same let me know if any issue arises.

**Comment by mmo-uy** [comment]
Thanks for your quick reply @SurajLad I had to remove this issue because I made it with my work's github account. This is personal account. I already take a look [https://github.com/SurajLad/Webinar_App-Flutter](url) and it looks promising. Thanks for your help
